name: Salesforce Deploy
on:
  push:
    branches:
      - main

jobs:
  InstallNode_And_Salesforce:
    runs-on: ubuntu-latest
    steps: 
      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Print My Name
        run: echo "Jeerawat"
      - name: Install Salesforce
        run: npm install @salesforce/cli --global
      - name: Salesforce Pring Core
        run: sf plugins --core
