name: Salesforce Deploy
on:
  push:
    branches:
      - main

jobs:
  Install_Node_And_Salesforce:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Salesforce
        run: npm install @salesforce/cli --global
      - name: Salesforce Pring Core
        run: sf plugins --core
      - name: Create Private Key
        run: echo "${{ secrets.P_KEY }}" >> private.Key
      - name: Salesforce Authen
        run: sf org login jwt --client-id ${{ secrets.JWT_TOKEN }} --jwt-key-file "private.Key" --username teerac35@comexpert.co.th.demodev --alias my-org --instance-url https://test.salesforce.com
      - name: Where am i 
        run: ${{echo pwd}}
